<!DOCTYPE html>
<header>
<nav id="global">
<ul>
<li><a href="index.html">Home</a> </li>
<li><a href="contactus.html">Contact Us</a></li> 
<li><a href="map.html">Map</a></li>
</ul>
</nav>

<div id="nameplate">
	<h1>&nbsp;</h1>
	</div>
	
<div id="infobox">
	<p>Chemists &amp; Consultants</p>
	</div>
<div id="mainimage1block"></div>	
<div id="mainimage2block"></div>
<div id="mainimage3block"></div>	
<div id="mainimage4block"></div>
	<!-- Start css3menu.com HEAD section -->
	<link rel="stylesheet" href="menu_web.css3prj_files/css3menu1/style.css" type="text/css" /><style>
._css3m{display:none}
																							   .auto-style1 {
																								   color: #FFFFFF;
																							   }
																							   		  .auto-style2 {
																											 text-align: center;
																											 color: #FFFFFF;
																										 }
																							   </style>
	<!-- End css3menu.com HEAD section -->

</header>

<article class="contentBox3">
<!-- #BeginEditable "bannerBox left" --> 
<p>
<a href="samplingguide.html">
<img alt="Sampling Guide" title="Sampling Guide" class="imageleft" height="100" src="images/image3.png" width="94"></a><strong>Sampling 
Guide</strong><br>Sampling Techniques for Soil and Plant Tissue<br>
<a href="samplingguide.html">READ MORE</a></p>

<!-- #EndEditable -->
</article>

<article class="contentBox3">
<!-- #BeginEditable "bannerBox middle" --> 
	<p><strong>
	<img alt="" class="imageleft" height="75" src="images/gears.png" width="80">Analytical Catalog</strong><br>
	Please call if you do not see what you need.<br>
	<a href="analyticalcatalog.html">READ MORE</a></p>
<!-- #EndEditable -->
</article>

<article class="contentBox3">
<!-- #BeginEditable "bannerBox right" --> 
	<p>
	<img alt="" class="imageleft" height="91" src="images/dellavallee_logo.png" width="286">&nbsp;</p>
<!-- #EndEditable -->
</article>