<!DOCTYPE html>
<header>
<nav id="global">
<ul>
<li><a href="index.html">Home</a> </li>
<li><a href="contactus.html">Contact Us</a></li> 
<li><a href="map.html">Map</a></li>
</ul>
</nav>

<div id="nameplate">
	<h1>&nbsp;</h1>
	</div>
	
<div id="infobox">
	<p>Chemists &amp; Consultants</p>
	</div>
<div id="mainimage1block"></div>	
<div id="mainimage2block"></div>
<div id="mainimage3block"></div>	
<div id="mainimage4block"></div>
	<!-- Start css3menu.com HEAD section -->
	<link rel="stylesheet" href="menu_web.css3prj_files/css3menu1/style.css" type="text/css" /><style>
._css3m{display:none}
																							   .auto-style1 {
																								   color: #FFFFFF;
																							   }
																							   		  .auto-style2 {
																											 text-align: center;
																											 color: #FFFFFF;
																										 }
																							   </style>
	<!-- End css3menu.com HEAD section -->

</header>